language: bash
addons:
  apt:
    sources:
    - debian-sid
    packages:
    - shellcheck
script:
- shellcheck -e SC2140 spotkey.sh
- bash spotkey.sh
before_install:
- openssl aes-256-cbc -K $encrypted_0fc5a16aa10e_key -iv $encrypted_0fc5a16aa10e_iv
  -in spotkey.conf.enc -out spotkey.conf -d
